# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven and push to Container Repo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Build with Maven
      run: mvn -B install --file pom.xml
    - name: Upload Java artifact
      uses: actions/upload-artifact@v2
      with:
        name: java_artifact
        path: target/*.jar
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Java artifact
        uses: actions/download-artifact@v2
        with:
          name: java_artifact
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to OCI
        uses: docker/login-action@v1 
        with:
          registry: phx.ocir.io
          username: ${{ secrets.ORACLE_CR_USERNAME }}
          password: ${{ secrets.ORACLE_CR_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags:  phx.ocir.io/jpginfra/progress-tracker:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
