# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven and push to Container Repo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Build with Maven
      run: mvn --batch-mode deploy javadoc:javadoc
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract Maven project version
      shell: bash
      run: $(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec) > version.txt
    - name: Upload Target Folder
      uses: actions/upload-artifact@v2
      with:
        name: target_folder
        path: target
    - name: Upload Artifact Version
      uses: actions/upload-artifact@v2
      with:
        name: artifact_version
        path: metadata/version.txt
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Target Folder
        uses: actions/download-artifact@v2
        with:
          name: target_folder
      - name: Download metadata
        uses: actions/download-artifact@v1
        with:
          name: artifact_version
      - name: Create version environment variable
        shell: bash
        run: |
          value=`cat metadata/version.txt`
          echo ::set-output name=version::$value
        id: project
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/progress-tracker:latest ${{ secrets.DOCKERHUB_USERNAME }}/progress-tracker:${{ steps.project.outputs.version }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
